// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIT8g__DlfQ3OJ3nMkmQkpR0Bqvr9geqs',
    appId: '1:481768842261:web:83f9f63da50ee3010fda1c',
    messagingSenderId: '481768842261',
    projectId: 'cyberbullyinapp-d427c',
    authDomain: 'cyberbullyinapp-d427c.firebaseapp.com',
    databaseURL: 'https://cyberbullyinapp-d427c-default-rtdb.firebaseio.com',
    storageBucket: 'cyberbullyinapp-d427c.firebasestorage.app',
    measurementId: 'G-FT52E74ZNZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDctSASv_gd2FeDlaZngN_QCnZM25e44oU',
    appId: '1:481768842261:android:5e81973af4ca858b0fda1c',
    messagingSenderId: '481768842261',
    projectId: 'cyberbullyinapp-d427c',
    databaseURL: 'https://cyberbullyinapp-d427c-default-rtdb.firebaseio.com',
    storageBucket: 'cyberbullyinapp-d427c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVuGxsxnFW4julpMjcb0tl7acud-3Eei4',
    appId: '1:481768842261:ios:8f2eb6e5c6553be60fda1c',
    messagingSenderId: '481768842261',
    projectId: 'cyberbullyinapp-d427c',
    databaseURL: 'https://cyberbullyinapp-d427c-default-rtdb.firebaseio.com',
    storageBucket: 'cyberbullyinapp-d427c.firebasestorage.app',
    iosClientId: '481768842261-5dk4ea6f4v13mo40b5917ou8b7r10r1p.apps.googleusercontent.com',
    iosBundleId: 'com.example.cyberApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVuGxsxnFW4julpMjcb0tl7acud-3Eei4',
    appId: '1:481768842261:ios:8f2eb6e5c6553be60fda1c',
    messagingSenderId: '481768842261',
    projectId: 'cyberbullyinapp-d427c',
    databaseURL: 'https://cyberbullyinapp-d427c-default-rtdb.firebaseio.com',
    storageBucket: 'cyberbullyinapp-d427c.firebasestorage.app',
    iosClientId: '481768842261-5dk4ea6f4v13mo40b5917ou8b7r10r1p.apps.googleusercontent.com',
    iosBundleId: 'com.example.cyberApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIT8g__DlfQ3OJ3nMkmQkpR0Bqvr9geqs',
    appId: '1:481768842261:web:b272ffa22a86c0f40fda1c',
    messagingSenderId: '481768842261',
    projectId: 'cyberbullyinapp-d427c',
    authDomain: 'cyberbullyinapp-d427c.firebaseapp.com',
    databaseURL: 'https://cyberbullyinapp-d427c-default-rtdb.firebaseio.com',
    storageBucket: 'cyberbullyinapp-d427c.firebasestorage.app',
    measurementId: 'G-B0GHY1H22R',
  );
}
