name: cyber_app
description: "Cyberbullying Detector mobile app."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  firebase_core: ^4.12.1
  firebase_auth: ^6.5.6
  file_saver: ^0.3.1
  pdf: ^3.11.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Noto Sans
      fonts:
        - asset: assets/fonts/NotoSans.ttf
    - family: Noto Sans Bengali
      fonts:
        - asset: assets/fonts/NotoSansBengali.ttf
